/** Survival tuning is shared by the renderer and interface; weapon/item tables live in domain.ts. */
export const SURVIVAL = {
    maxHealth: 100,
    maxStamina: 100,
    carryLimit: 24,
    walkSpeed: 112,
    sprintSpeed: 190,
    aimSpeedFactor: 0.7,
    overloadSlowdownPerKg: 0.045,
    sprintDrain: 24,
    staminaRecovery: 15,
    exhaustedAt: 5,
    sprintRecoveryAt: 25,
    bleedChance: 0.18,
    bleedDamage: 0.65,
    pollutionHighTide: 7,
    pollutionLowTide: 2.5,
    pollutionRecovery: 0.2,
    pollutionDamageThreshold: 70,
    pollutionDamageBase: 60,
    pollutionDamageFactor: 0.06,
    bandageHeal: 16,
    medkitHeal: 55,
    waterCleanse: 12,
    foodStamina: 50,
    foodHeal: 12,
    antidoteCleanse: 55,
    gunNoiseRange: 510,
    sprintNoiseRange: 180,
    extractionSeconds: 3,
} as const;
